font_sets = {
    "display": [
        "garden/assets/fonts/Anton/Anton-Regular.ttf",
        "garden/assets/fonts/ArchivoBlack/ArchivoBlack-Regular.ttf",
        "garden/assets/fonts/BebasNeue/BebasNeue-Regular.ttf",
        "garden/assets/fonts/Righteous/Righteous-Regular.ttf",
        "garden/assets/fonts/Audiowide/Audiowide-Regular.ttf",
        "garden/assets/fonts/Monoton/Monoton-Regular.ttf",
        "garden/assets/fonts/Oswald/Oswald-Bold.ttf",
        "garden/assets/fonts/Staatliches/Staatliches-Regular.ttf",
        "garden/assets/fonts/AbrilFatface/AbrilFatface-Regular.ttf",
    ],
    "script": [
        "garden/assets/fonts/GreatVibes/GreatVibes-Regular.ttf",
        "garden/assets/fonts/Pacifico/Pacifico-Regular.ttf",
        "garden/assets/fonts/Lobster/Lobster-Regular.ttf",
        "garden/assets/fonts/DancingScript/DancingScript-Regular.ttf",
        "garden/assets/fonts/DancingScript/DancingScript-Bold.ttf",
        "garden/assets/fonts/Sacramento/Sacramento-Regular.ttf",
    ],
    "hand": [
        "garden/assets/fonts/PermanentMarker/PermanentMarker-Regular.ttf",
        "garden/assets/fonts/ShadowsIntoLight/ShadowsIntoLight-Regular.ttf",
        "garden/assets/fonts/Caveat/Caveat-Regular.ttf",
        "garden/assets/fonts/Caveat/Caveat-Bold.ttf",
        "garden/assets/fonts/RockSalt/RockSalt-Regular.ttf",
    ],
    "rounded": [
        "garden/assets/fonts/BubblegumSans/BubblegumSans-Regular.ttf",
        "garden/assets/fonts/FredokaOne/FredokaOne-Regular.ttf",
        "garden/assets/fonts/Baloo2/Baloo2-Regular.ttf",
        "garden/assets/fonts/Baloo2/Baloo2-Bold.ttf",
        "garden/assets/fonts/Comfortaa/Comfortaa-Regular.ttf",
        "garden/assets/fonts/Comfortaa/Comfortaa-Bold.ttf",
        "garden/assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf",
        "garden/assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf",
        "garden/assets/fonts/Cinzel/Cinzel-Regular.ttf",
        "garden/assets/fonts/Cinzel/Cinzel-Bold.ttf",
    ],
}