# Generated by Django 6.0.5 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_paypalsubscription_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(default='SERVICE', max_length=50)),
                ('category', models.CharField(default='SOFTWARE', max_length=80)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
