# Generated by Django 6.0.5 on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_paypalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='paypalProductId',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypalProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_fk', to='subscription.paypalproduct'),
        ),
        migrations.AddField(
            model_name='paypalproduct',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, related_name='paypal_products', to='subscription.subscriptionplan'),
        ),
    ]
