# Generated by Django 6.0.5 on 2026-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_rename_paypalsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='billing_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='cycle_executions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='failed_payments_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='last_payment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='last_payment_amount_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='last_payment_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='paypal_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='paypal_status_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='quantity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='shipping_amount_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='shipping_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paypalcustomersubscription',
            name='subscriber',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
