# Generated by Django 6.0.5 on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_paypalcustomersubscription_user"),
        ("userProfile", "0012_userposter_paypal_customer_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS subscription_usersubscription;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="paypalcustomersubscription",
                    name="due_date",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="paypalproduct",
                    name="paymongo_product_id",
                    field=models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="subscriptionplan",
                    name="paymongo_plan_id",
                    field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="paypalproduct",
            name="paypal_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RenameField(
            model_name="paypalcustomersubscription",
            old_name="plan_id",
            new_name="paypal_plan_id",
        ),
        migrations.AddField(
            model_name="paypalcustomersubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_subscriptions",
                to="subscription.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="paypalcustomersubscription",
            name="paymongo_customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paypalcustomersubscription",
            name="paymongo_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paypalcustomersubscription",
            name="paypal_plan_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paypalcustomersubscription",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paypalcustomersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("CREATED", "Created"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paypalcustomersubscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameModel(
            old_name="PayPalCustomerSubscription",
            new_name="UserSubscription",
        ),
    ]
