# Generated by Django 6.0.5 on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_rename_paypalcustomersubscription_usersubscription"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PayPalProduct",
            new_name="SubscriptionProduct",
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="paypalProduct",
            new_name="subscriptionProduct",
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="subscriptionProduct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_fk",
                to="subscription.subscriptionproduct",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="subscription_plans",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscription_products",
                to="subscription.subscriptionplan",
            ),
        ),
    ]
