# Generated by Django 6.0.5 on 2026-05-26 00:12

import django.db.models.deletion
import subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_rename_paypalproduct_subscriptionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('public_id', models.CharField(default=subscription.models.source_website_public_id, editable=False, max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('default_success_url', models.URLField(blank=True, null=True)),
                ('default_cancel_url', models.URLField(blank=True, null=True)),
                ('default_failed_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=subscription.models.payment_button_public_id, editable=False, max_length=40, unique=True)),
                ('label', models.CharField(default='Subscribe Now', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('checkout_mode', models.CharField(choices=[('hosted_checkout', 'Hosted Checkout'), ('paymongo_recurring', 'PayMongo Recurring')], default='hosted_checkout', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('cancel_url', models.URLField(blank=True, null=True)),
                ('failed_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_buttons', to='subscription.subscriptionplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_buttons', to='subscription.subscriptionproduct')),
                ('source_website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_buttons', to='subscription.sourcewebsite')),
            ],
            options={
                'ordering': ['source_website__name', 'product__name', 'plan__price'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('paymongo_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='subscription.sourcewebsite')),
            ],
            options={
                'ordering': ['email', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference_id', models.CharField(db_index=True, default=subscription.models.transaction_reference_id, editable=False, max_length=40, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=180, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checkout_created', 'Checkout Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_centavos', models.PositiveIntegerField()),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('paymongo_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('paymongo_payment_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('paymongo_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('paymongo_subscription_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('paymongo_status', models.CharField(blank=True, max_length=80, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('raw_checkout_request', models.JSONField(blank=True, default=dict)),
                ('raw_checkout_response', models.JSONField(blank=True, default=dict)),
                ('raw_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscription.customer')),
                ('payment_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscription.paymentbutton')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscription.subscriptionplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscription.subscriptionproduct')),
                ('source_website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscription.sourcewebsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('paymongo_subscription_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymongo_subscriptions', to='subscription.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymongo_subscriptions', to='subscription.subscriptionplan')),
                ('source_website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.sourcewebsite')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to='subscription.transaction')),
            ],
            options={
                'ordering': ['-current_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayMongoWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymongo_event_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('signature_header', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('failed', 'Failed')], default='received', max_length=30)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscription.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
