# Generated by Django 6.0.5 on 2026-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_alter_subscriptionplan_billinginterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbutton',
            name='payment_link_reference',
            field=models.CharField(blank=True, db_index=True, help_text='PayMongo payment link reference number, for example b5vnlvt.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paymentbutton',
            name='payment_link_url',
            field=models.URLField(blank=True, help_text='Existing PayMongo payment link URL, for example https://pm.link/org-.../b5vnlvt.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymongo_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymongo_reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='paymentbutton',
            name='checkout_mode',
            field=models.CharField(choices=[('hosted_checkout', 'Hosted Checkout'), ('paymongo_recurring', 'PayMongo Recurring'), ('paymongo_link', 'PayMongo Payment Link')], default='hosted_checkout', max_length=30),
        ),
    ]
