# Generated by Django 6.0.5 on 2026-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_paymentbutton_payment_link_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_billing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
