# Generated by Django 6.0.5 on 2026-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_transaction_customer_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_cancelled', 'Incomplete Cancelled'), ('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('CREATED', 'Created'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('UNPAID', 'Unpaid'), ('SUSPENDED', 'Suspended'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='pending', max_length=50),
        ),
    ]
