# Generated by Django 4.2.30 on 2026-09-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0027_packages_rating_average_packages_rating_count_and_more'),
        ('subscription', '0014_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='resort_package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_product', to='resorts.packages'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billingInterval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], max_length=20),
        ),
    ]
