# Generated by Django 4.2.30 on 2026-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_subscriptionproduct_resort_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbutton',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
