# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionTheme', models.CharField(blank=True, choices=[('orange', 'orange'), ('green', 'green'), ('violet', 'violet'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow')], max_length=24, null=True)),
                ('collectionLocalFile', models.CharField(blank=True, max_length=1000, null=True)),
                ('collectionImageIndicator', models.CharField(blank=True, max_length=1000, null=True)),
                ('collectionName', models.CharField(max_length=128)),
                ('collectionDescription', models.TextField()),
                ('collectionPicture', models.URLField(blank=True, null=True)),
                ('collectionUniqueID', models.CharField(blank=True, max_length=500, null=True)),
                ('collectionIsCollected', models.BooleanField(default=False)),
                ('collectionTimstamp', models.DateTimeField(auto_now_add=True)),
                ('collectionCollected', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoryPicture', models.URLField()),
                ('memoryAbout', models.TextField()),
                ('memoryisPrivate', models.BooleanField(default=False)),
                ('memoryTimestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeCollections', models.CharField(blank=True, max_length=64, null=True)),
                ('placeName', models.CharField(max_length=64)),
                ('placePicture', models.URLField()),
                ('placeisVisited', models.BooleanField(default=False)),
                ('placeLastVisited', models.DateTimeField(auto_now=True)),
                ('placeFirstVisited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='testClastt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorName', models.CharField(max_length=64)),
                ('visitorID', models.CharField(max_length=12)),
                ('visitorTimestamp', models.DateTimeField(auto_now_add=True)),
                ('visitorCollections', models.ManyToManyField(blank=True, related_name='visitorcollectionlists', to='garden.collection')),
                ('visitorMemories', models.ManyToManyField(blank=True, related_name='visitorcollectionlists', to='garden.memory')),
                ('visitorPlaces', models.ManyToManyField(blank=True, related_name='visitedPlaceLists', to='garden.placeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=64)),
                ('provincePlaces', models.ManyToManyField(blank=True, related_name='provinceplacelists', to='garden.placeprofile')),
                ('provinceVisitor', models.ManyToManyField(blank=True, related_name='provincevisitorlists', to='garden.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='placeprofile',
            name='placeProvince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetPlace', to='garden.province'),
        ),
        migrations.AddField(
            model_name='placeprofile',
            name='placeVisitor',
            field=models.ManyToManyField(blank=True, related_name='placeVisitorLists', to='garden.visitor'),
        ),
        migrations.AddField(
            model_name='memory',
            name='memoryVisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitormemorylists', to='garden.visitor'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collectionCollector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetCollector', to='garden.visitor'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collectionMemory',
            field=models.ManyToManyField(blank=True, related_name='provinceplacelists', to='garden.memory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collectionPlace',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetPlace', to='garden.placeprofile'),
        ),
    ]
