# Generated by Django 4.2.23 on 2025-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionVideo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
