# Generated by Django 4.2.23 on 2025-12-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_allschedules_monthn'),
        ('garden', '0002_collection_collectionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionPlaceDirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetPlaceDirect', to='home.places_v2'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collectionDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
