# Generated by Django 4.2.23 on 2025-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_collection_collectionplacedirect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collectionTheme',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('gold', 'Gold'), ('champagne', 'Champagne'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('ruby', 'Ruby'), ('rose-gold', 'Rose Gold'), ('platinum', 'Platinum'), ('pearl', 'Pearl'), ('bronze', 'Bronze')], max_length=24, null=True),
        ),
    ]
