# Generated by Django 4.2.23 on 2025-12-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_allschedules_daten_and_more'),
        ('garden', '0004_alter_collection_collectiontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='touristSpot',
            field=models.ManyToManyField(blank=True, related_name='touristspotcollections', to='home.touristspot'),
        ),
    ]
