# Generated by Django 4.2.23 on 2026-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_collection_touristspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionGoogleDriveURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
