# Generated by Django 4.2.23 on 2026-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_collection_collectiongoogledriveurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='groups', to='garden.collection')),
            ],
        ),
    ]
