# Generated by Django 4.2.23 on 2026-04-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_collectiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primaryCollections', to='garden.collectiongroup'),
        ),
    ]
