# Generated by Django 4.2.23 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0008_collection_collectiongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectiongroup",
            name="address",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
