# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
        ('resorts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=15)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('checked_in', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='ResortManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_visitor', models.ManyToManyField(related_name='checked_visitor', to='resortManagement.checkins')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resort_manager', to='userProfile.userposter')),
            ],
        ),
        migrations.AddField(
            model_name='checkins',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_by', to='resortManagement.resortmanager'),
        ),
        migrations.AddField(
            model_name='checkins',
            name='resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resort', to='resorts.resortitem'),
        ),
        migrations.AddField(
            model_name='checkins',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='resorts.packages'),
        ),
        migrations.CreateModel(
            name='CheckinDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_days', to='resorts.packages')),
            ],
        ),
    ]
