# Generated by Django 4.2.23 on 2025-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkins',
            name='id_picture',
            field=models.URLField(blank=True),
        ),
    ]
