# Generated by Django 4.2.23 on 2025-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0002_checkins_id_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkins',
            name='id_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
