# Generated by Django 4.2.23 on 2025-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0003_alter_checkins_id_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinday',
            name='checkinday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinday',
            name='checkoutday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
