# Generated by Django 4.2.23 on 2025-11-04 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0004_checkinday_checkinday_checkinday_checkoutday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinday',
            name='checkinday',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinday',
            name='checkoutday',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
