# Generated by Django 4.2.23 on 2025-12-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0017_remove_packagesiargaoevent_use_auto_m2m'),
        ('resortManagement', '0005_alter_checkinday_checkinday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused')], default='pending', max_length=10)),
                ('auto_renew', models.BooleanField(default=False)),
                ('last_payment_reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='resortManagement.resortmanager')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='resorts.resortitem')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
