# Generated by Django 4.2.30 on 2026-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0007_resortbookingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortbookingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
