# Generated by Django 4.2.30 on 2026-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0008_alter_resortbookingpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortbookingpayment',
            name='receipt_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
