# Generated by Django 4.2.30 on 2026-09-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_subscription_status_and_more'),
        ('resortManagement', '0009_resortbookingpayment_receipt_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortbookingpayment',
            name='payment_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resort_booking_payments', to='subscription.paymentbutton'),
        ),
        migrations.AddField(
            model_name='resortbookingpayment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resort_booking_payments', to='subscription.subscriptionplan'),
        ),
    ]
