# Generated by Django 6.0.5 on 2026-09-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortManagement', '0010_resortbookingpayment_payment_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resortbookingpayment',
            name='payment_button',
        ),
        migrations.RemoveField(
            model_name='resortbookingpayment',
            name='subscription_plan',
        ),
    ]
