# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetchID', models.IntegerField(default=1)),
                ('detailsContact', models.CharField(default='+639568543802', max_length=94)),
                ('posterVerified', models.BooleanField(default=False)),
                ('posterID', models.IntegerField(default=1)),
                ('posterName', models.CharField(default='Anonymous', max_length=64)),
                ('posterURL', models.URLField(blank=True, default='http://none.com')),
                ('posterImageURL', models.URLField(blank=True)),
                ('scheduleImageURL', models.URLField(blank=True, default=0)),
                ('posterReputation', models.IntegerField(default=0)),
                ('scheduleID', models.IntegerField(blank=True, null=True)),
                ('posterInstagram', models.CharField(blank=True, max_length=64)),
                ('dateN', models.IntegerField(blank=True, default=3)),
                ('monthN', models.IntegerField(blank=True, default=9)),
                ('yearN', models.IntegerField(blank=True, default=2025)),
                ('additionalDetails', models.TextField(blank=True)),
                ('otherDetails', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewCount', models.IntegerField(default=0)),
                ('meetPlace', models.CharField(blank=True, max_length=64)),
                ('meetTime', models.CharField(blank=True, max_length=24, null=True)),
                ('endDate', models.CharField(blank=True, max_length=64)),
                ('scheduleTitle', models.CharField(blank=True, max_length=64)),
                ('scheduleCost', models.CharField(blank=True, max_length=64)),
                ('scheduleWebsite', models.URLField(blank=True, null=True)),
                ('scheduleTravelType', models.CharField(blank=True, max_length=64)),
                ('MakerOrLooker', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderID', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('messanger', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(default='website', max_length=64)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaceDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.TextField()),
                ('discusserName', models.CharField(default='ANONYMOUS', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('requesting_ip', models.GenericIPAddressField()),
                ('timesmtamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResortMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(default='Anonymous', max_length=32)),
                ('resortID', models.IntegerField()),
                ('guestMessage', models.TextField()),
                ('guestContact', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SchedTypeAndMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeName', models.CharField(max_length=24)),
                ('scheduleObject', models.ManyToManyField(blank=True, related_name='SchedLists', to='home.allschedules')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('last_request', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'page')},
            },
        ),
        migrations.CreateModel(
            name='Places_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewCount', models.IntegerField(default=0)),
                ('placeID', models.IntegerField(blank=True, default=0, null=True)),
                ('placename', models.CharField(max_length=64)),
                ('placePhoto', models.CharField(blank=True, max_length=9999)),
                ('discussion', models.ManyToManyField(blank=True, related_name='discussionsLists', to='home.placediscussion')),
                ('placesSchedules', models.ManyToManyField(blank=True, related_name='allScheds', to='home.allschedules')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
