# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resorts', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places_v2',
            name='resortItem',
            field=models.ManyToManyField(blank=True, related_name='RESORTS_OF_PLACE', to='resorts.resortitem'),
        ),
        migrations.AddField(
            model_name='placediscussion',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placediscuss', to='home.places_v2'),
        ),
        migrations.AddField(
            model_name='comment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postSchedule', to='home.allschedules'),
        ),
    ]
