# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allschedules',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='commentList', to='home.comment'),
        ),
        migrations.AddField(
            model_name='allschedules',
            name='schedulePlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivingTo', to='home.places_v2'),
        ),
    ]
