# Generated by Django 4.2.23 on 2025-09-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='page',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='requestpage',
            name='page_name',
            field=models.CharField(max_length=555),
        ),
    ]
