# Generated by Django 4.2.23 on 2025-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_allschedules_daten_alter_requestlog_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=15),
        ),
    ]
