# Generated by Django 4.2.23 on 2025-09-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_requestlog_location_alter_allschedules_daten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='location',
            new_name='ip_location',
        ),
    ]
