# Generated by Django 4.2.23 on 2025-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='ip_location_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
