# Generated by Django 4.2.23 on 2025-09-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_requestlog_ip_location_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='ip_location',
            new_name='ip_location_json',
        ),
    ]
