# Generated by Django 4.2.23 on 2025-09-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_ip_location_requestlog_ip_location_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='ip_location_json',
        ),
    ]
