# Generated by Django 4.2.23 on 2025-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_requestlog_ip_location_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='ip_location_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
