# Generated by Django 4.2.23 on 2025-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_requestlog_ip_location_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='places_v2',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
