# Generated by Django 4.2.23 on 2025-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_places_v2_slug_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places_v2',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]

