# Generated by Django 4.2.23 on 2025-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_places_v2_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places_v2',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
