# Generated by Django 4.2.23 on 2025-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_places_v2_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='allschedules',
            name='scheduleTypeAndMode',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
