# Generated by Django 4.2.23 on 2025-10-06 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_allschedules_scheduletypeandmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='timesmtamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=6),
        ),
    ]
