# Generated by Django 4.2.23 on 2025-10-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_requestlog_timesmtamp_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='requestPages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestLogs', to='home.requestpage'),
        ),
    ]
