# Generated by Django 4.2.23 on 2025-10-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_requestlog_requestpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='requestPages',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='requestPages',
            field=models.ManyToManyField(blank=True, related_name='requestLogsList', to='home.requestpage'),
        ),
    ]
