# Generated by Django 4.2.23 on 2025-10-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_requestlog_requestpages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=16),
        ),
        migrations.AlterField(
            model_name='places_v2',
            name='placePhoto',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
