# Generated by Django 4.2.23 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_allschedules_daten_alter_places_v2_placephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=26),
        ),
    ]
