# Generated by Django 4.2.23 on 2025-10-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=28),
        ),
    ]
