# Generated by Django 4.2.23 on 2025-11-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_blogs_blogplace'),
        ('home', '0026_alter_allschedules_daten_alter_allschedules_monthn'),
    ]

    operations = [
        migrations.AddField(
            model_name='places_v2',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='bloglists', to='apis.blogs'),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=11),
        ),
    ]
