# Generated by Django 4.2.23 on 2025-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_places_v2_blog_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=12),
        ),
    ]
