# Generated by Django 4.2.23 on 2025-12-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_allschedules_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=12),
        ),
    ]
