# Generated by Django 4.2.23 on 2025-12-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_allschedules_daten'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiargaoEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterName', models.CharField(default='Anonymous', max_length=64)),
                ('posterURL', models.URLField(blank=True, default='http://none.com')),
                ('posterImageURL', models.URLField(blank=True)),
                ('posterVerified', models.BooleanField(default=False)),
                ('posterID', models.IntegerField(default=0)),
                ('posterReputation', models.IntegerField(default=0)),
                ('scheduleTitle', models.CharField(blank=True, max_length=200)),
                ('scheduleWebsite', models.URLField(blank=True, null=True)),
                ('scheduleImageURL', models.URLField(blank=True)),
                ('scheduleTypeAndMode', models.CharField(blank=True, max_length=64, null=True)),
                ('schedulePlace', models.CharField(blank=True, max_length=255)),
                ('meetPlace', models.CharField(blank=True, max_length=64)),
                ('meetTime', models.CharField(blank=True, max_length=24, null=True)),
                ('endDate', models.CharField(blank=True, max_length=64)),
                ('scheduleCost', models.CharField(blank=True, max_length=64)),
                ('dateN', models.IntegerField(blank=True, default=13)),
                ('monthN', models.IntegerField(blank=True, default=12)),
                ('yearN', models.IntegerField(blank=True, default=2025)),
                ('additionalDetails', models.TextField(blank=True)),
                ('otherDetails', models.TextField(blank=True, null=True)),
                ('locations_json', models.TextField(blank=True)),
                ('backgroundURL', models.URLField(blank=True)),
                ('thumbnailURL', models.URLField(blank=True)),
                ('markerURL', models.URLField(blank=True)),
                ('host_name', models.CharField(blank=True, max_length=64)),
                ('host_link', models.URLField(blank=True)),
                ('fetchID', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventPlace', to='home.places_v2')),
            ],
        ),
        migrations.AddField(
            model_name='places_v2',
            name='evenSchedules',
            field=models.ManyToManyField(blank=True, related_name='eventSchedulesLists', to='home.siargaoeventschedule'),
        ),
    ]
