# Generated by Django 4.2.23 on 2025-12-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_siargaoeventschedule_places_v2_evenschedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places_v2',
            old_name='evenSchedules',
            new_name='eventSchedules',
        ),
    ]
