# Generated by Django 4.2.23 on 2025-12-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_evenschedules_places_v2_eventschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='siargaoeventschedule',
            name='exactDate',
            field=models.CharField(blank=True, max_length=304),
        ),
    ]
