# Generated by Django 4.2.23 on 2025-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_touristspot_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='coords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='spot_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
