# Generated by Django 4.2.23 on 2025-12-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_description_touristspot_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='img',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
