# Generated by Django 4.2.23 on 2025-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_touristspot_img_alter_touristspot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
