# Generated by Django 4.2.23 on 2025-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_alter_resortitem_slug'),
        ('home', '0039_touristspot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='resortItem',
            field=models.ManyToManyField(blank=True, related_name='TOURIST_SPOTS_OF_RESORT', to='resorts.resortitem'),
        ),
    ]
