# Generated by Django 4.2.23 on 2025-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_touristspot_resortitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='spot_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
