# Generated by Django 4.2.23 on 2025-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_touristspot_spot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=18),
        ),
    ]
