# Generated by Django 4.2.23 on 2025-12-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiargaoEventRegistrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('pax', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='home.siargaoeventschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='siargaoeventregistrant',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='uniq_siargao_event_reg_email'),
        ),
    ]
