# Generated by Django 4.2.23 on 2025-12-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_siargaoeventregistrant'),
        ('resorts', '0017_remove_packagesiargaoevent_use_auto_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='siargaoeventschedule',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siargao_event_schedules', to='resorts.packages'),
        ),
    ]
