# Generated by Django 4.2.23 on 2025-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
