# Generated by Django 4.2.23 on 2025-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_usercredentials_ip_address_and_more'),
        ('home', '0052_touristspot_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='tourguide',
            field=models.ManyToManyField(blank=True, related_name='spots_guided', to='userProfile.tourguide'),
        ),
    ]
