# Generated by Django 4.2.23 on 2025-12-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_touristspot_tourguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=28),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=28),
        ),
    ]
