# Generated by Django 4.2.23 on 2025-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='scheduleTypeAndMode',
            field=models.CharField(blank=True, choices=[('carpool', 'Carpool'), ('tour', 'Tour')], max_length=34, null=True),
        ),
    ]
