# Generated by Django 4.2.23 on 2025-12-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0055_alter_allschedules_scheduletypeandmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='allschedules',
            name='endPlace',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='allschedules',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Joiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pickLocation', models.CharField(blank=True, max_length=128)),
                ('pickCoordinate', models.CharField(blank=True, max_length=128)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joinerList', to='home.allschedules')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allschedules',
            name='joinerUser',
            field=models.ManyToManyField(blank=True, related_name='joinerUsers', to='home.joiner'),
        ),
    ]
