# Generated by Django 4.2.23 on 2025-12-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_allschedules_endplace_allschedules_poster_joiner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiner',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
