# Generated by Django 4.2.23 on 2025-12-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(default='Too many 404 errors', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='requestpage',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
