# Generated by Django 4.2.23 on 2025-12-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_blockedip_requestpage_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiner',
            name='contact',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
