# Generated by Django 4.2.23 on 2025-12-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_joiner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='detailsContact',
            field=models.CharField(default='', max_length=94),
        ),
    ]
