# Generated by Django 4.2.23 on 2025-12-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_requestpagesummary_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='scheduleTypeAndMode',
            field=models.CharField(blank=True, choices=[('carpool', 'Carpool')], max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
