# Generated by Django 4.2.23 on 2025-12-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestpagesummary',
            old_name='region',
            new_name='continent_name',
        ),
        migrations.AddField(
            model_name='requestpagesummary',
            name='country_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
