# Generated by Django 4.2.23 on 2025-12-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_rename_region_requestpagesummary_continent_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpagesummary',
            options={'ordering': ['-total_requests', '-latest_timesmtamp', 'requesting_ip']},
        ),
    ]
