# Generated by Django 4.2.23 on 2026-01-04 06:49

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_requestpagesummary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='yearN',
            field=models.IntegerField(blank=True, default=2026),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='monthN',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='yearN',
            field=models.IntegerField(blank=True, default=2026),
        ),
        migrations.CreateModel(
            name='CommunityBulletinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ai_title', models.CharField(blank=True, max_length=160)),
                ('ai_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_bulletin_posts', to='home.places_v2')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBulletinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models._community_bulletin_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.communitybulletinpost')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
