# Generated by Django 4.2.23 on 2026-01-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_allschedules_daten_alter_allschedules_monthn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitybulletinimage',
            name='image',
        ),
        migrations.AddField(
            model_name='communitybulletinimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
