# Generated by Django 4.2.23 on 2026-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_remove_communitybulletinimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybulletinimage',
            name='imgbb_delete_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='communitybulletinimage',
            name='imgbb_delete_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
