# Generated by Django 4.2.23 on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0069_communitybulletinimage_imgbb_delete_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitybulletinpost",
            name="social_posting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitybulletinpost",
            name="social_posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
