# Generated by Django 4.2.23 on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0070_communitybulletinpost_social_posting"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitybulletinpost",
            name="social_last_error",
            field=models.TextField(blank=True),
        ),
    ]
