# Generated by Django 4.2.23 on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0071_communitybulletinpost_social_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookPagePost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fb_post_id", models.CharField(max_length=128, unique=True)),
                ("message", models.TextField(blank=True)),
                ("permalink_url", models.URLField(blank=True, max_length=2000)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("media_json", models.JSONField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_time", "-imported_at"],
            },
        ),
    ]
