# Generated by Django 4.2.23 on 2026-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_facebookpagepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpagesummary',
            options={'ordering': ['-unique_pages', '-latest_timesmtamp', 'requesting_ip']},
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=9),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=9),
        ),
    ]
