# Generated by Django 4.2.23 on 2026-01-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_requestpagesummary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('about', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name='places_v2',
            name='facebook_pages',
            field=models.ManyToManyField(blank=True, related_name='places', to='home.facebookpage'),
        ),
    ]
