# Generated by Django 4.2.23 on 2026-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_facebookpage_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpagesummary',
            options={'ordering': ['-updated_at', '-latest_timesmtamp', 'unique_pages']},
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=21),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=21),
        ),
    ]
