# Generated by Django 4.2.23 on 2026-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_requestpagesummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siargaoeventregistrant',
            name='event_date',
            field=models.CharField(blank=True, max_length=304),
        ),
    ]
