# Generated by Django 4.2.23 on 2026-01-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_touristspot_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
