# Generated by Django 4.2.23 on 2026-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_touristspot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siargaoeventschedule',
            name='endPlace',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=26),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=26),
        ),
    ]
