# Generated by Django 4.2.23 on 2026-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_siargaoeventschedule_endplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='monthN',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
