# Generated by Django 4.2.23 on 2026-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_allschedules_daten_alter_allschedules_monthn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpagesummary',
            options={'ordering': ['earliest_timesmtamp', '-latest_timesmtamp', 'unique_pages']},
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
