# Generated by Django 4.2.23 on 2026-03-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0084_alter_allschedules_daten_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allschedules",
            name="dateN",
            field=models.IntegerField(blank=True, default=29),
        ),
        migrations.AlterField(
            model_name="siargaoeventschedule",
            name="dateN",
            field=models.IntegerField(blank=True, default=29),
        ),
    ]
