# Generated by Django 4.2.23 on 2026-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0085_alter_allschedules_daten_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allschedules",
            name="dateN",
            field=models.IntegerField(blank=True, default=21),
        ),
        migrations.AlterField(
            model_name="allschedules",
            name="monthN",
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name="siargaoeventschedule",
            name="dateN",
            field=models.IntegerField(blank=True, default=21),
        ),
        migrations.AlterField(
            model_name="siargaoeventschedule",
            name="monthN",
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
