# Generated by Django 4.2.23 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0086_alter_allschedules_daten_alter_allschedules_monthn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allschedules",
            name="dateN",
            field=models.IntegerField(blank=True, default=23),
        ),
        migrations.AlterField(
            model_name="siargaoeventschedule",
            name="dateN",
            field=models.IntegerField(blank=True, default=23),
        ),
    ]
