# Generated by Django 6.0.5 on 2026-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=26),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=26),
        ),
    ]
