# Generated by Django 6.0.5 on 2026-06-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_alter_allschedules_daten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=14),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=14),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='monthN',
            field=models.IntegerField(blank=True, default=6),
        ),
    ]
