# Generated by Django 6.0.5 on 2026-06-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_alter_allschedules_daten_alter_allschedules_monthn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=96)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='home.continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='home.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceDirectory',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='directory', serialize=False, to='home.places_v2')),
                ('place_type', models.PositiveSmallIntegerField(choices=[(0, 'Unspecified'), (1, 'Destination'), (2, 'Beach'), (3, 'Island'), (4, 'City'), (5, 'Mountain'), (6, 'Attraction'), (7, 'Resort area')], default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.continent')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.region')),
            ],
            options={
                'ordering': ['-popularity_score', 'place_id'],
                'indexes': [models.Index(fields=['is_published', '-popularity_score', 'place'], name='pd_pub_pop_idx'), models.Index(fields=['country', 'is_published', '-popularity_score', 'place'], name='pd_country_pub_pop_idx'), models.Index(fields=['region', 'is_published', '-popularity_score', 'place'], name='pd_region_pub_pop_idx'), models.Index(fields=['continent', 'place_type', 'is_published', '-popularity_score', 'place'], name='pd_cont_type_pub_idx')],
            },
        ),
    ]
