# Generated by Codex on 2026-06-16

from django.db import migrations


def backfill_place_directory(apps, schema_editor):
    PlacesV2 = apps.get_model("home", "Places_v2")
    PlaceDirectory = apps.get_model("home", "PlaceDirectory")

    batch = []
    batch_size = 1000

    queryset = PlacesV2.objects.only("id", "reviewCount").order_by("id")
    for place in queryset.iterator(chunk_size=batch_size):
        batch.append(
            PlaceDirectory(
                place_id=place.id,
                place_type=0,
                is_published=True,
                popularity_score=max(0, int(place.reviewCount or 0)),
            )
        )
        if len(batch) >= batch_size:
            PlaceDirectory.objects.bulk_create(
                batch,
                batch_size=batch_size,
                ignore_conflicts=True,
            )
            batch.clear()

    if batch:
        PlaceDirectory.objects.bulk_create(
            batch,
            batch_size=batch_size,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0097_place_directory"),
    ]

    operations = [
        migrations.RunPython(backfill_place_directory, migrations.RunPython.noop),
    ]
