# Generated by Django 4.2.30 on 2026-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_backfill_place_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='dateN',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='monthN',
            field=models.IntegerField(blank=True, default=9),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='dateN',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AlterField(
            model_name='siargaoeventschedule',
            name='monthN',
            field=models.IntegerField(blank=True, default=9),
        ),
    ]
