# Generated by Django 4.2.23 on 2025-09-03 04:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_initial'),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_room_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_item_ID', models.IntegerField(blank=True, null=True)),
                ('admin_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('receiver', models.CharField(blank=True, max_length=64, null=True)),
                ('sender', models.CharField(blank=True, max_length=64, null=True)),
                ('chat_room_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usesrID', models.IntegerField(default=0)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[400, 400], upload_to='UserProfileImages2')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentialsBackUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userPassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='userPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, default='Facebook not Connected', max_length=64)),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('photo', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verificationID', models.URLField(blank=True)),
                ('upVote', models.IntegerField(default=0)),
                ('downVote', models.IntegerField(default=0)),
                ('registeredTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('reputations', models.IntegerField(default=1)),
                ('signedFrom', models.CharField(blank=True, max_length=64)),
                ('folderLink', models.URLField(blank=True)),
                ('member_ID', models.URLField(blank=True)),
                ('member_type', models.CharField(default='Associate Member', max_length=32)),
                ('hashes', models.TextField(default='')),
                ('chatRoomslists', models.ManyToManyField(blank=True, related_name='chatroomlistofitem', to='userProfile.chat_room_item')),
                ('myTransactions', models.ManyToManyField(blank=True, related_name='User_TransactionList', to='apis.transaction')),
                ('posts', models.ManyToManyField(blank=True, related_name='postLists', to='home.allschedules')),
                ('visitedUser', models.ManyToManyField(blank=True, related_name='visitedList', to='userProfile.userposter')),
                ('visitorUser', models.ManyToManyField(blank=True, related_name='visitorList', to='userProfile.userposter')),
            ],
            options={
                'unique_together': {('userID', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('photoLink', models.URLField(blank=True)),
                ('additionalCreds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.userposter')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
