# Generated by Django 4.2.23 on 2025-12-19 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_allschedules_daten_and_more'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_link', models.URLField(blank=True, help_text="Link to tour guide's profile or website")),
                ('bio', models.TextField(blank=True, help_text='Brief biography of the tour guide')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience as a tour guide')),
                ('languages', models.CharField(blank=True, help_text='Languages spoken (comma-separated)', max_length=255)),
                ('certifications', models.TextField(blank=True, help_text='Tour guide certifications or licenses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tourist_spots', models.ManyToManyField(blank=True, related_name='tour_guides', to='home.touristspot')),
                ('tours', models.ManyToManyField(blank=True, related_name='guided_tours', to='home.allschedules')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Guide',
                'verbose_name_plural': 'Tour Guides',
            },
        ),
    ]
