# Generated by Django 4.2.23 on 2025-12-19 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_tourguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='guided_tourists',
            field=models.ManyToManyField(blank=True, help_text='Tourists currently being guided by this tour guide', related_name='guided_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
