# Generated by Django 4.2.23 on 2025-12-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_tourguide_guided_tourists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='profile_link',
        ),
    ]
