# Generated by Django 4.2.23 on 2025-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_remove_tourguide_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for contact', max_length=15),
        ),
    ]
