# Generated by Django 4.2.23 on 2025-12-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_tourguide_mobile_number'),
    ]

    operations = [
    ]
