# Generated by Django 4.2.23 on 2025-12-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_allschedules_daten_and_more'),
        ('userProfile', '0006_auto_20251219_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='primary_place',
            field=models.ForeignKey(blank=True, help_text='Primary place where this tour guide operates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_guides', to='home.places_v2'),
        ),
    ]
