# Generated by Django 4.2.23 on 2025-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_tourguidetourist_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposter',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_plus', '65+'), ('prefer_not_to_disclose', 'Prefer not to disclose')], max_length=32),
        ),
        migrations.AddField(
            model_name='userposter',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_disclose', 'Prefer not to disclose')], max_length=32),
        ),
    ]
