# Generated by Django 4.2.23 on 2025-12-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_userposter_age_range_userposter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address at registration/login', null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='referrer_url',
            field=models.URLField(blank=True, help_text='Page they came from during registration'),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device info'),
        ),
    ]
