# Generated by Django 4.2.23 on 2026-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_requestpagesummary_options_and_more'),
        ('userProfile', '0010_usercredentials_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='visitedPlace',
            field=models.ManyToManyField(blank=True, help_text='Places this user has visited', related_name='visited_users', to='home.places_v2'),
        ),
    ]
