# Generated by Django 6.0.5 on 2026-05-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_paypalcustomersubscription_user'),
        ('userProfile', '0011_usercredentials_visitedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposter',
            name='paypal_customer_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_posters', to='subscription.paypalcustomersubscription'),
        ),
    ]
