# Generated by Django 6.0.5 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_rename_paypalcustomersubscription_usersubscription"),
        ("userProfile", "0012_userposter_paypal_customer_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userposter",
            old_name="paypal_customer_subscription",
            new_name="user_subscription",
        ),
        migrations.AlterField(
            model_name="userposter",
            name="user_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_posters",
                to="subscription.usersubscription",
            ),
        ),
    ]
