# Generated by Django 6.0.5 on 2026-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_rename_paypal_customer_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposter',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userposter',
            name='address_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userposter',
            name='address_line1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='userposter',
            name='address_line2',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='userposter',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userposter',
            name='address_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userposter',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userposter',
            name='paymongo_billing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
