# Generated by Codex on 2026-05-28

from django.db import migrations, models
import userProfile.instapay


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_userposter_address_city_userposter_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposter',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userposter',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userposter',
            name='bank_contact',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userposter',
            name='bank_name',
            field=models.CharField(
                blank=True,
                choices=userProfile.instapay.INSTAPAY_BANK_CHOICES,
                max_length=160,
            ),
        ),
    ]
