# Generated by Django 4.2.23 on 2025-09-11 01:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='googleimagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usesrID', models.IntegerField(default=0)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[400, 400], upload_to='googleimagemodelBackUP')),
            ],
        ),
    ]
