# Generated by Django 4.2.23 on 2025-09-11 02:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_googleimagemodel_timesmtamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleimagemodel',
            name='googleURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='imbbURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='googleimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[400, 400], upload_to='imageuploaded'),
        ),
    ]
