# Generated by Django 4.2.23 on 2025-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_googleimagemodel_googleurl_googleimagemodel_imbburl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleimagemodel',
            name='imageclassID',
            field=models.IntegerField(default=0),
        ),
    ]
