# Generated by Django 4.2.23 on 2025-11-12 03:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_googleimagemodel_imageclassid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[400, 400], upload_to='imageuploaded'),
        ),
    ]
