# Generated by Django 4.2.23 on 2025-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0005_alter_googleimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleimagemodel',
            name='imageclassID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
