# Generated by Django 6.0.5 on 2026-05-10 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0006_alter_googleimagemodel_imageclassid'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleimagemodel',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='ip_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='referrer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='source',
            field=models.CharField(blank=True, help_text='Where they subscribed from', max_length=100),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='unsubscribe_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='unsubscribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleimagemodel',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
