# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField(blank=True)),
                ('shortsay', models.CharField(blank=True, max_length=124)),
                ('profile', models.URLField(blank=True)),
                ('bloggerURL', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customTime', models.CharField(blank=True, max_length=64)),
                ('ImageUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('postUrl', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('context', models.TextField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=64)),
                ('longitude', models.CharField(blank=True, max_length=64)),
                ('placename', models.CharField(blank=True, max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionNo', models.CharField(blank=True, max_length=64)),
                ('lastChainTransactionNo', models.CharField(max_length=64)),
                ('hash', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
