# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
        ('apis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmedbytrack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatorTransaction', to='userProfile.userposter'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetTransaction', to='userProfile.userposter'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='BlogsBlogger', to='apis.blogs'),
        ),
    ]
