# Generated by Django 4.2.23 on 2025-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='resort_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
