# Generated by Django 4.2.23 on 2025-11-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_allschedules_daten_alter_allschedules_monthn'),
        ('apis', '0003_payments_amount_payments_payer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blogplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogplaceitem', to='home.places_v2'),
        ),
    ]
