# Generated by Django 4.2.23 on 2025-11-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_blogs_blogplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='placename',
            new_name='localurlpath',
        ),
    ]
