# Generated by Django 4.2.23 on 2025-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_placename_blogs_localurlpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='ImageUrl',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='context',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='customTime',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='localurlpath',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='postUrl',
        ),
    ]
