# Generated by Django 4.2.23 on 2025-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_blogs_imageurl_remove_blogs_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='localurlpath',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
