# Generated by Django 4.2.23 on 2025-12-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_blogs_localurlpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, choices=[('Guide', 'Guide'), ('Tip and Trick', 'Tip and Trick'), ('Explore', 'Explore')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='readtime',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='blogs',
            name='summarize',
            field=models.CharField(default='Learn more about <django.db.models.fields.CharField>', max_length=400),
        ),
    ]
