# Generated by Django 4.2.23 on 2025-12-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_blogs_category_blogs_readtime_blogs_summarize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('Guide', 'Guide'), ('Tip and Trick', 'Tip and Trick'), ('Explore', 'Explore')], default='Guide', max_length=24),
        ),
    ]
