# Generated by Django 4.2.23 on 2025-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='summarize',
            field=models.CharField(default='Discover more about this destination', max_length=400),
        ),
    ]
