# Generated by Django 4.2.23 on 2025-12-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_blogs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('email_open_count', models.IntegerField(default=0)),
                ('link_click_count', models.IntegerField(default=0)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant - Every new post'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('monthly', 'Monthly Digest')], default='weekly', max_length=20)),
                ('interested_categories', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, help_text='Where they subscribed from', max_length=100)),
                ('referrer_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('unsubscribe_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email Subscriber',
                'verbose_name_plural': 'Email Subscribers',
                'ordering': ['-subscribed_date'],
            },
        ),
    ]
