# Generated by Django 6.0.5 on 2026-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_emailsubscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storeproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('affiliate_link', models.URLField(blank=True)),
            ],
        ),
    ]
