# Generated by Django 6.0.5 on 2026-05-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_storeproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='textContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
