# Generated by Django 6.0.5 on 2026-05-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_blogs_textcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('Guide', 'Guide'), ('Story', 'Story'), ('Tip and Trick', 'Tip and Trick'), ('Explore', 'Explore'), ('Product', 'Product')], default='Guide', max_length=24),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=6400),
        ),
    ]
