# Generated by Django 6.0.5 on 2026-05-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_blogs_category_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='localurlpath',
            field=models.CharField(blank=True, max_length=2555),
        ),
    ]
