# Generated by Codex on 2026-05-24

from django.db import migrations, models
from django.utils import timezone


def backfill_blog_datetimes(apps, schema_editor):
    Blogs = apps.get_model("apis", "Blogs")
    now = timezone.now()
    for blog in Blogs.objects.only("id", "timestamp"):
        value = blog.timestamp or now
        Blogs.objects.filter(pk=blog.pk).update(
            created_at=value,
            updated_at=value,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0016_alter_blogs_localurlpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogs",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.RunPython(backfill_blog_datetimes, migrations.RunPython.noop),
    ]
