# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0017_blogs_created_at_blogs_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="last_updated_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
