# Generated by Django 6.0.5 on 2026-06-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_blogs_last_updated_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
