# Generated by Django 6.0.5 on 2026-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_alter_blogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogs',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='blogs',
            name='faq_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='searchable_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
