# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investorID', models.IntegerField(default=0)),
                ('investedAmount', models.IntegerField()),
                ('investedValue', models.IntegerField()),
                ('investedProfit', models.IntegerField()),
                ('contractRatio', models.FloatField(default=0)),
                ('investedDividend', models.IntegerField(default=0)),
                ('deliveredDividend', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('timestamp2', models.DateTimeField(auto_now_add=True)),
                ('investedPercentageBefore', models.FloatField(default=0)),
                ('investedPercentageAfter', models.FloatField(default=0)),
                ('CurrentiClubValue', models.IntegerField(default=0)),
                ('invest_valueBefore', models.IntegerField(default=0)),
                ('investor_name', models.CharField(max_length=64)),
                ('invest_amount', models.IntegerField()),
                ('investor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SideComputations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearComputation', models.IntegerField(default=2022)),
                ('MonthComputation', models.IntegerField(blank=True, default=1)),
                ('DateComputation', models.IntegerField(blank=True, default=1)),
                ('InterestComputation', models.FloatField(default=0)),
                ('ProfitComputation', models.IntegerField(default=0)),
                ('side', models.CharField(max_length=32)),
                ('sideAmount', models.IntegerField(blank=True, default=0)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StocksHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockQuantity', models.IntegerField()),
                ('stockBuyPrice', models.FloatField()),
                ('stockName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Total_Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('average', models.FloatField(blank=True, default=0)),
                ('balance', models.IntegerField(default=0)),
                ('gatheredAmount', models.IntegerField(blank=True, default=0)),
                ('stock', models.CharField(max_length=64)),
                ('portfolioValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=32)),
                ('stockQuantity', models.IntegerField(default=0)),
                ('TransactionSide', models.CharField(max_length=32)),
                ('stockPrice', models.FloatField()),
                ('CostAfterTax', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestType', models.CharField(blank=True, max_length=32)),
                ('interest', models.FloatField(blank=True, default=0)),
                ('duration', models.CharField(blank=True, max_length=32)),
                ('investor_name', models.CharField(max_length=64)),
                ('investor_contact', models.CharField(blank=True, max_length=64)),
                ('invested_percentage', models.FloatField(default=0)),
                ('invested_amount', models.IntegerField(default=0)),
                ('invested_value', models.IntegerField(default=0)),
                ('reinvested', models.DateTimeField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dividendsReceived', models.ManyToManyField(blank=True, related_name='dividendGiven', to='calculator.dividendrecord')),
                ('investmentHistory', models.ManyToManyField(blank=True, related_name='investrecordhistory', to='calculator.investmentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InterestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('FixInterest', models.ManyToManyField(blank=True, related_name='fixList', to='calculator.investor')),
                ('GrowthInterest', models.ManyToManyField(blank=True, related_name='growthList', to='calculator.investor')),
                ('RatioInterest', models.ManyToManyField(blank=True, related_name='ratioList', to='calculator.investor')),
            ],
        ),
    ]
