from django.forms import ModelForm
from django import forms
from .models import Blogger,Blogs, EmailSubscribers


class BloggerForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Blogger
        fields = '__all__'

class BlogsForm(forms.ModelForm):
    """Form for creating blogs - title, summary, and readtime are auto-generated by OpenAI"""
    class Meta:
        model = Blogs
        fields = ['category', 'blogplace', 'latitude', 'longitude']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select'}),
            'blogplace': forms.Select(attrs={'class': 'form-select', 'required': True}),
            'latitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Optional: 9.8627'}),
            'longitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Optional: 126.0125'}),
        }
        labels = {
            'blogplace': '📍 Location/Place',
            'category': '📂 Category',
            'latitude': '🗺️ Latitude (Optional)',
            'longitude': '🗺️ Longitude (Optional)',
        }

class EmailSubscriberForm(forms.ModelForm):
    """Form for blog email subscriptions - simplified for footer forms"""
    class Meta:
        model = EmailSubscribers
        fields = ['email', 'name']
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control', 
                'placeholder': 'your@email.com',
                'required': True
            }),
            'name': forms.TextInput(attrs={
                'class': 'form-control', 
                'placeholder': 'Your name (optional)'
            }),
        }
        labels = {
            'email': '📧 Email Address',
            'name': '👤 Name',
        }

# from django.forms import ModelForm
# from django import forms
# from .models import ImageModel

#  class="form-control-file"
# class ImageForm(forms.ModelForm):

#     """Form for the image model"""
#     class Meta:
#         model = ImageModel
#         fields = ('image',)
#         widgets = {
#             "image": forms.FileInput(attrs={'onchange': "this.form.submit()",'class':"custom-file-input", 'id':"validatedCustomFile" })
#         }
