# Generated by Django 3.2.6 on 2022-08-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleID', models.IntegerField(blank=True, null=True)),
                ('posterInstagram', models.CharField(blank=True, max_length=64)),
                ('dateN', models.IntegerField(blank=True, null=True)),
                ('monthN', models.IntegerField(blank=True)),
                ('yearN', models.IntegerField(blank=True)),
                ('detailsContact', models.CharField(max_length=94)),
                ('additionalDetails', models.TextField(blank=True)),
                ('otherDetails', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewCount', models.IntegerField(default=0)),
                ('meetPlace', models.CharField(blank=True, max_length=64)),
                ('meetTime', models.CharField(blank=True, max_length=24, null=True)),
                ('endDate', models.CharField(blank=True, max_length=64)),
                ('scheduleTitle', models.CharField(blank=True, max_length=64)),
                ('scheduleCost', models.CharField(blank=True, max_length=64)),
                ('scheduleWebsite', models.URLField(blank=True, null=True)),
                ('scheduleTypeAndMode', models.CharField(blank=True, max_length=34)),
                ('scheduleTravelType', models.CharField(blank=True, max_length=64)),
                ('MakerOrLooker', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Places_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewCount', models.IntegerField(default=0)),
                ('placeID', models.IntegerField(blank=True, default=0, null=True)),
                ('placename', models.CharField(max_length=64)),
                ('placePhoto', models.CharField(blank=True, max_length=9999)),
                ('placesSchedules', models.ManyToManyField(blank=True, related_name='allScheds', to='home.allSchedules')),
            ],
        ),
        migrations.AddField(
            model_name='allschedules',
            name='schedulePlace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivingTo', to='home.places_v2'),
        ),
    ]
