# Generated by Django 3.2.6 on 2022-08-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userposter'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allschedules',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.userposter'),
        ),
    ]
