# Generated by Django 3.2.6 on 2022-08-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_allschedules_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('messanger', models.CharField(max_length=64)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postSchedule', to='home.allschedules')),
            ],
        ),
        migrations.AddField(
            model_name='allschedules',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='home.Comment'),
        ),
    ]
