# Generated by Django 3.2.6 on 2022-08-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220831_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allschedules',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='commentList', to='home.Comment'),
        ),
    ]
