# Generated by Django 3.2.6 on 2022-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='allschedules',
            name='posterName',
            field=models.CharField(default='John Doe', max_length=64),
        ),
    ]
