# Generated by Django 3.2.6 on 2022-09-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20220831_1154'),
        ('home', '0006_allschedules_postername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places_v2',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='PlaceDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discusser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusserUser', to='userProfile.userposter')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placediscuss', to='home.places_v2')),
            ],
        ),
        migrations.AddField(
            model_name='places_v2',
            name='discussion',
            field=models.ManyToManyField(blank=True, related_name='discussionsLists', to='home.PlaceDiscussion'),
        ),
    ]
