# Generated by Django 3.2.6 on 2022-09-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20220831_1154'),
        ('home', '0007_auto_20220903_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='placediscussion',
            name='discusserName',
            field=models.CharField(default='ANONYMOUS', max_length=64),
        ),
        migrations.AlterField(
            model_name='placediscussion',
            name='discusser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discusserUser', to='userProfile.userposter'),
        ),
    ]
