# Generated by Django 3.2.6 on 2022-09-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20220831_1154'),
        ('home', '0008_auto_20220903_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placediscussion',
            name='discusser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discusserUser', to='userProfile.userposter'),
        ),
    ]
