# Generated by Django 3.2.6 on 2022-09-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_placediscussion_discusser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestMessage', models.TextField()),
                ('guestContact', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='allschedules',
            name='posterName',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
    ]
