# Generated by Django 3.2.6 on 2022-09-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220903_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortmessages',
            name='resortID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
