# Generated by Django 3.2.6 on 2022-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_resortmessages_resortid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortmessages',
            name='guestName',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
    ]
