# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='resortItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resortQRLink', models.URLField(blank=True, null=True)),
                ('resort_ID', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('RealName', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('contactNumber', models.CharField(blank=True, max_length=128)),
                ('contactEmail', models.CharField(blank=True, max_length=128)),
                ('promotionalVideo', models.URLField(blank=True)),
                ('virtualpicture', models.URLField(blank=True)),
                ('headerImage', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=63)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sideImagesURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlField', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='resortPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageTitle', models.CharField(max_length=64)),
                ('ItemOfResort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemOfResort', to='resorts.resortitem')),
                ('subPackages', models.ManyToManyField(blank=True, related_name='packagesOfActivities', to='resorts.packages')),
            ],
        ),
    ]
