# Generated by Django 4.2.23 on 2025-09-03 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resorts', '0001_initial'),
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='adminManager',
            field=models.ManyToManyField(blank=True, related_name='resortAdmins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EstablishmentPlace', to='home.places_v2'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='registeredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='resortAccomodations',
            field=models.ManyToManyField(blank=True, related_name='packages_of_accomodations', to='resorts.resortpackages'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='resortActivities',
            field=models.ManyToManyField(blank=True, related_name='packages_of_activities', to='resorts.resortpackages'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='resortSchedules',
            field=models.ManyToManyField(blank=True, related_name='resortScheduleList', to='home.allschedules'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='resortTour',
            field=models.ManyToManyField(blank=True, related_name='packages_of_tour', to='resorts.resortpackages'),
        ),
        migrations.AddField(
            model_name='packages',
            name='ImageURL',
            field=models.ManyToManyField(blank=True, related_name='imagesOfSide', to='resorts.sideimagesurls'),
        ),
        migrations.AddField(
            model_name='packages',
            name='packageName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppa', to='resorts.resortpackages'),
        ),
    ]
