# Generated by Django 4.2.23 on 2025-10-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='resortGallery',
            field=models.ManyToManyField(blank=True, null=True, to='resorts.sideimagesurls'),
        ),
    ]
