# Generated by Django 4.2.23 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_resortitem_resortgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortitem',
            name='resortGallery',
            field=models.ManyToManyField(blank=True, to='resorts.sideimagesurls'),
        ),
    ]
