# Generated by Django 4.2.23 on 2025-10-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_alter_resortitem_resortgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
