# Generated by Django 4.2.23 on 2025-10-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_alter_resortitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortitem',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
