# Generated by Django 4.2.23 on 2025-12-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_alter_resortitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='websiteURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
