# Generated by Django 4.2.23 on 2025-12-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_resortitem_websiteurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='resortFood',
            field=models.ManyToManyField(blank=True, related_name='packages_of_food', to='resorts.resortpackages'),
        ),
    ]
