# Generated by Django 4.2.23 on 2025-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0010_resortitem_resortfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
