# Generated by Django 4.2.23 on 2025-12-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0011_packages_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='whatsappNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
