# Generated by Django 4.2.23 on 2025-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0012_resortitem_whatsappnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
