# Generated by Django 4.2.23 on 2025-12-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_allschedules_daten_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resorts', '0013_packages_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='last_visited',
            field=models.DateTimeField(blank=True, help_text='Last time a manager visited or updated this resort.', null=True),
        ),
        migrations.CreateModel(
            name='InactiveResortItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resortQRLink', models.URLField(blank=True, null=True)),
                ('websiteURL', models.URLField(blank=True, null=True)),
                ('resort_ID', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('RealName', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('contactNumber', models.CharField(blank=True, max_length=128)),
                ('contactEmail', models.CharField(blank=True, max_length=128)),
                ('whatsappNumber', models.CharField(blank=True, max_length=128)),
                ('promotionalVideo', models.URLField(blank=True)),
                ('virtualpicture', models.URLField(blank=True)),
                ('headerImage', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=63)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('last_visited', models.DateTimeField(blank=True, help_text='Last time a manager visited or updated this resort.', null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
                ('adminManager', models.ManyToManyField(blank=True, related_name='inactive_resortAdmins', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InactiveEstablishmentPlace', to='home.places_v2')),
                ('registeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactive_registeredBy', to=settings.AUTH_USER_MODEL)),
                ('resortAccomodations', models.ManyToManyField(blank=True, related_name='inactive_packages_of_accomodations', to='resorts.resortpackages')),
                ('resortActivities', models.ManyToManyField(blank=True, related_name='inactive_packages_of_activities', to='resorts.resortpackages')),
                ('resortFood', models.ManyToManyField(blank=True, related_name='inactive_packages_of_food', to='resorts.resortpackages')),
                ('resortGallery', models.ManyToManyField(blank=True, to='resorts.sideimagesurls')),
                ('resortSchedules', models.ManyToManyField(blank=True, related_name='inactive_resortScheduleList', to='home.allschedules')),
                ('resortTour', models.ManyToManyField(blank=True, related_name='inactive_packages_of_tour', to='resorts.resortpackages')),
            ],
        ),
    ]
