# Generated by Django 4.2.23 on 2025-12-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0014_resortitem_last_visited_inactiveresortitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('pax', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event/promo item being registered for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='resorts.packages')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='resorts.resortitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='uniq_event_registration_email'),
        ),
    ]
