# Generated by Django 4.2.23 on 2025-12-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_siargaoeventregistrant'),
        ('resorts', '0015_eventregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSiargaoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.packages')),
                ('siargao_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.siargaoeventschedule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='packagesiargaoevent',
            constraint=models.UniqueConstraint(fields=('package', 'siargao_event'), name='uniq_pkg_siargao_event'),
        ),
        migrations.AddField(
            model_name='packages',
            name='siargaoevents',
            field=models.ManyToManyField(blank=True, related_name='packages', through='resorts.PackageSiargaoEvent', to='home.siargaoeventschedule'),
        ),
    ]
