# Generated by Django 4.2.23 on 2025-12-26

from django.db import migrations, models


def forwards_copy_links(apps, schema_editor):
    Packages = apps.get_model('resorts', 'Packages')
    PackageSiargaoEvent = apps.get_model('resorts', 'PackageSiargaoEvent')

    # Copy links from explicit through table to the temporary auto M2M
    for link in PackageSiargaoEvent.objects.all().iterator():
        try:
            pkg = Packages.objects.get(id=link.package_id)
            pkg.siargaoevents_temp.add(link.siargao_event_id)
        except Exception:
            continue


def backwards_copy_links(apps, schema_editor):
    # Best-effort reverse: if someone rolls back, attempt to repopulate the explicit through table
    Packages = apps.get_model('resorts', 'Packages')
    PackageSiargaoEvent = apps.get_model('resorts', 'PackageSiargaoEvent')

    for pkg in Packages.objects.all().iterator():
        try:
            for ev_id in pkg.siargaoevents_temp.values_list('id', flat=True):
                PackageSiargaoEvent.objects.get_or_create(package_id=pkg.id, siargao_event_id=ev_id)
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0016_package_siargao_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='siargaoevents_temp',
            field=models.ManyToManyField(blank=True, related_name='packages_temp', to='home.siargaoeventschedule'),
        ),
        migrations.RunPython(forwards_copy_links, backwards_copy_links),
        migrations.RemoveField(
            model_name='packages',
            name='siargaoevents',
        ),
        migrations.DeleteModel(
            name='PackageSiargaoEvent',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='siargaoevents_temp',
            new_name='siargaoevents',
        ),
        migrations.AlterField(
            model_name='packages',
            name='siargaoevents',
            field=models.ManyToManyField(blank=True, related_name='packages', to='home.siargaoeventschedule'),
        ),
    ]
