# Generated by Django 4.2.23 on 2025-12-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0017_remove_packagesiargaoevent_use_auto_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactiveresortitem',
            name='family_friendly',
            field=models.BooleanField(default=False, help_text='Family-friendly facilities'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, help_text='Air conditioning in rooms'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_bar',
            field=models.BooleanField(default=False, help_text='Bar/lounge available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_beach_access',
            field=models.BooleanField(default=False, help_text='Direct beach access'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_bidet',
            field=models.BooleanField(default=False, help_text='Bidet in comfort rooms'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_breakfast',
            field=models.BooleanField(default=False, help_text='Breakfast included/available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_generator',
            field=models.BooleanField(default=False, help_text='Backup generator available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_gym',
            field=models.BooleanField(default=False, help_text='Fitness center/gym'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_hot_water',
            field=models.BooleanField(default=False, help_text='Hot water available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_laundry',
            field=models.BooleanField(default=False, help_text='Laundry service available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_pool',
            field=models.BooleanField(default=False, help_text='Swimming pool available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_restaurant',
            field=models.BooleanField(default=False, help_text='On-site restaurant'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_spa',
            field=models.BooleanField(default=False, help_text='Spa services available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='has_wifi',
            field=models.BooleanField(default=False, help_text='Free WiFi available'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Pets allowed'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='family_friendly',
            field=models.BooleanField(default=False, help_text='Family-friendly facilities'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, help_text='Air conditioning in rooms'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_bar',
            field=models.BooleanField(default=False, help_text='Bar/lounge available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_beach_access',
            field=models.BooleanField(default=False, help_text='Direct beach access'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_bidet',
            field=models.BooleanField(default=False, help_text='Bidet in comfort rooms'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_breakfast',
            field=models.BooleanField(default=False, help_text='Breakfast included/available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_generator',
            field=models.BooleanField(default=False, help_text='Backup generator available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_gym',
            field=models.BooleanField(default=False, help_text='Fitness center/gym'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_hot_water',
            field=models.BooleanField(default=False, help_text='Hot water available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_laundry',
            field=models.BooleanField(default=False, help_text='Laundry service available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_pool',
            field=models.BooleanField(default=False, help_text='Swimming pool available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_restaurant',
            field=models.BooleanField(default=False, help_text='On-site restaurant'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_spa',
            field=models.BooleanField(default=False, help_text='Spa services available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='has_wifi',
            field=models.BooleanField(default=False, help_text='Free WiFi available'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Pets allowed'),
        ),
    ]
