# Generated by Django 4.2.23 on 2025-12-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0018_inactiveresortitem_family_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactiveresortitem',
            name='accepts_cash',
            field=models.BooleanField(default=False, help_text='Accepts cash payment'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='accepts_credit_card',
            field=models.BooleanField(default=False, help_text='Accepts credit card payment'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='accepts_debit_card',
            field=models.BooleanField(default=False, help_text='Accepts debit card payment'),
        ),
        migrations.AddField(
            model_name='inactiveresortitem',
            name='accepts_gcash',
            field=models.BooleanField(default=False, help_text='Accepts GCash payment'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='accepts_cash',
            field=models.BooleanField(default=False, help_text='Accepts cash payment'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='accepts_credit_card',
            field=models.BooleanField(default=False, help_text='Accepts credit card payment'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='accepts_debit_card',
            field=models.BooleanField(default=False, help_text='Accepts debit card payment'),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='accepts_gcash',
            field=models.BooleanField(default=False, help_text='Accepts GCash payment'),
        ),
    ]
