# Generated by Django 4.2.23 on 2025-12-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0020_packages_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactiveresortitem',
            name='open_hours',
            field=models.CharField(blank=True, default='', help_text='Example: Mon–Sun 8:00 AM – 9:00 PM', max_length=128),
        ),
        migrations.AddField(
            model_name='resortitem',
            name='open_hours',
            field=models.CharField(blank=True, default='', help_text='Example: Mon–Sun 8:00 AM – 9:00 PM', max_length=128),
        ),
    ]
