# Generated by Django 4.2.23 on 2026-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0021_inactiveresortitem_open_hours_resortitem_open_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveresortitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inactiveresortitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
