# Generated by Django 4.2.23 on 2026-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0022_alter_inactiveresortitem_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveresortitem',
            name='websiteURL',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='resortitem',
            name='websiteURL',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
