# Generated by Django 4.2.23 on 2026-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0023_alter_inactiveresortitem_websiteurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
