# Generated by Django 4.2.23 on 2026-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0024_resortitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='date',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
