# Generated by Django 4.2.23 on 2026-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0025_eventregistration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
